[package]
name = "ttgo-camera"
version = "0.1.0"
authors = ["George C. Huntington III <ghuntington@hubbell.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.71"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = ["std", "embassy", "esp-idf-svc/native"]

pio = ["esp-idf-svc/pio"]
std = ["alloc", "esp-idf-svc/binstart", "esp-idf-svc/std"]
alloc = ["esp-idf-svc/alloc"]
nightly = ["esp-idf-svc/nightly"]
experimental = ["esp-idf-svc/experimental"]
embassy = ["esp-idf-svc/embassy-sync", "esp-idf-svc/critical-section", "esp-idf-svc/embassy-time-driver"]

[dependencies]
log = { version = "0.4", default-features = false }
embedded-svc = { version = "0.26.4", default-features = false, features = ["std"]}
esp-idf-svc = { version = "0.47.3", default-features = false }
esp-idf-hal = "0.42.5"
esp-idf-sys = "0.33.7"
ssd1306 = "0.8.4"
embedded-graphics = "0.8.1"
image = { version = "0.24.7", default-features = false, features = ["bmp", "jpeg"] }
toml-cfg = "=0.1.3"
libc = "0.2.151"
anyhow = "1.0.75"
edge-executor = "0.4.1"
# embedded-hal-async = "1.0.0-rc.3"

[build-dependencies]
embuild = "0.31.3"
toml-cfg = "=0.1.3"

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/esp32-camera", version = "2.0.6" }
bindings_header = "bindings.h"
bindings_module = "camera"
#component_dirs = "esp32-camera"
# remote_component = { name = "espressif/esp32-camera"}
#git = "https://github.com/espressif/esp32-camera.git"

